name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu20
    strategy:
      matrix:
        pair:
          - otp: "25"
            elixir: "1.14"
          - otp: "24"
            elixir: "1.14"
          - otp: "25"
            elixir: "1.13"
          - otp: "24"
            elixir: "1.13"
          - otp: "24"
            elixir: "1.12"
          - otp: "23"
            elixir: "1.12"
          - otp: "22"
            elixir: "1.11"
          - otp: "21"
            elixir: "1.11"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.pair.elixir }}
        otp-version: ${{ matrix.pair.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.pair.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Check Formatting
      run: mix format --check-formatted
